name: Build SLAMD macOS App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install py2app
        pip install -r requirements.txt

    - name: Remove old build artifacts
      run: |
        rm -rf build dist

    - name: Build app with py2app
      run: |
        python setup.py py2app

    - name: Upload SLAMD macOS app
      uses: actions/upload-artifact@v4
      with:
        name: SLAMD-macOS-app
        path: dist/SLAMD.app
