name: Build SLAMD macOS App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install production dependencies only
      run: |
        python -m pip install --upgrade pip
        pip install py2app
        pip install flask jinja2 py4j lolopy werkzeug pandas numpy scipy scikit-learn plotly

    - name: Clean build directories
      run: |
        rm -rf build dist

    - name: Build app (clean run)
      run: |
        rm -rf build dist
        python setup.py py2app


    - name: Upload .app as artifact
      uses: actions/upload-artifact@v4
      with:
        name: SLAMD-macOS-app
        path: dist/SLAMD.app
