name: Build SLAMD macOS App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install production dependencies only
      run: |
        python -m pip install --upgrade pip
        pip install py2app
        pip install flask jinja2 py4j lolopy werkzeug pandas numpy scipy scikit-learn plotly

    - name: Clean build directories
      run: |
        rm -rf build dist *.egg-info

    - name: Build app
      run: |
        python setup.py py2app

    - name: Zip app bundle
      run: |
        cd dist && zip -r SLAMD.app.zip SLAMD.app

    - name: Upload zipped .app bundle
      uses: actions/upload-artifact@v4
      with:
        name: SLAMD-macOS-App
        path: dist/SLAMD.app.zip
